
package View;
import View.ChucNang.*;
import java.awt.CardLayout;
import UI.ButtonColorHandler;
import javax.swing.SwingUtilities;

/**
 *
 * @author PC
 */
public class Menu extends javax.swing.JFrame {

    private ButtonColorHandler buttonColorHandler;
    private PanelPhieuMuon panelPhieuMuon;
    private PanelPhieuTra panelPhieuTra;

    public Menu() {
        initComponents();
        PanelSach panelKhoSach = new PanelSach();
        PanelTacGia panelTacGia = new PanelTacGia();// tạo instance từ class KhoSach
        PanelNhaXuatBan panelNhaXuatBan = new PanelNhaXuatBan();
        PanelTheLoai panelTheLoai = new PanelTheLoai();
        PanelSuKien panelSuKien = new PanelSuKien();       
        PanelMuonPhong panelMuonPhong = new PanelMuonPhong();
        PanelPhieuMuon panelPhieuMuon = new PanelPhieuMuon();
        PanelPhieuTra panelPhieuTra = new PanelPhieuTra();
        
        panelContent.add(panelNhaXuatBan, "nhaXuatBan");
        panelContent.add(panelKhoSach, "sach");
        panelContent.add(panelTacGia, "tacGia");// thêm vào CardLayout với tên
        panelContent.add(panelTheLoai, "theLoai");
        panelContent.add(panelSuKien, "suKien");
        panelContent.add(panelMuonPhong, "muonPhong");
        panelContent.add(panelPhieuMuon, "phieuMuon");
        panelContent.add(panelPhieuTra, "phieuTra");

        
        panelContent.setVisible(false); // <== Thêm dòng này để ẩn ban đầu
        
        buttonColorHandler = new ButtonColorHandler(
            btnSach, btnPhieuMuon, btnHocSinh, btnNhanVien, btnTacGia,
            btnNhaXuatBan, btnTaiKhoan, btnSuKien, btnMuonPhong, btnTheLoai,    
            btnThongKe, btnPhieuTra
        );
    }
        public PanelPhieuMuon getPanelPhieuMuon() {
        return panelPhieuMuon;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuLayout = new javax.swing.JPanel();
        btnNhanVien = new javax.swing.JButton();
        btnSach = new javax.swing.JButton();
        btnPhieuMuon = new javax.swing.JButton();
        btnHocSinh = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        btnTaiKhoan = new javax.swing.JButton();
        btnNhaXuatBan = new javax.swing.JButton();
        btnTacGia = new javax.swing.JButton();
        btnSuKien = new javax.swing.JButton();
        btnMuonPhong = new javax.swing.JButton();
        btnTheLoai = new javax.swing.JButton();
        btnPhieuTra = new javax.swing.JButton();
        panelLogo = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        panelContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));

        MenuLayout.setPreferredSize(new java.awt.Dimension(230, 768));

        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarian.png"))); // NOI18N
        btnNhanVien.setText("DS NHÂN VIÊN");
        btnNhanVien.setBackground(new java.awt.Color(42, 71, 89));
        btnNhanVien.setBorder(null);
        btnNhanVien.setFocusPainted(false);
        btnNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnNhanVien.setForeground(new java.awt.Color(238, 238, 238));
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });

        btnSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/book.png"))); // NOI18N
        btnSach.setText("KHO SÁCH");
        btnSach.setBackground(new java.awt.Color(42, 71, 89));
        btnSach.setBorder(null);
        btnSach.setBorderPainted(false);
        btnSach.setFocusPainted(false);
        btnSach.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnSach.setForeground(new java.awt.Color(238, 238, 238));
        btnSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSachActionPerformed(evt);
            }
        });

        btnPhieuMuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phieuMuon.png"))); // NOI18N
        btnPhieuMuon.setText("PHIẾU MƯỢN");
        btnPhieuMuon.setBackground(new java.awt.Color(42, 71, 89));
        btnPhieuMuon.setBorder(null);
        btnPhieuMuon.setFocusPainted(false);
        btnPhieuMuon.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnPhieuMuon.setForeground(new java.awt.Color(238, 238, 238));
        btnPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhieuMuonActionPerformed(evt);
            }
        });

        btnHocSinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student.png"))); // NOI18N
        btnHocSinh.setText("DS SINH VIÊN");
        btnHocSinh.setBackground(new java.awt.Color(42, 71, 89));
        btnHocSinh.setBorder(null);
        btnHocSinh.setFocusPainted(false);
        btnHocSinh.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnHocSinh.setForeground(new java.awt.Color(238, 238, 238));
        btnHocSinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHocSinhActionPerformed(evt);
            }
        });

        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thongKe.png"))); // NOI18N
        btnThongKe.setText("THỐNG KÊ");
        btnThongKe.setBackground(new java.awt.Color(42, 71, 89));
        btnThongKe.setBorder(null);
        btnThongKe.setFocusPainted(false);
        btnThongKe.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnThongKe.setForeground(new java.awt.Color(238, 238, 238));
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        btnTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/account.png"))); // NOI18N
        btnTaiKhoan.setText("TÀI KHOẢN");
        btnTaiKhoan.setBackground(new java.awt.Color(42, 71, 89));
        btnTaiKhoan.setBorder(null);
        btnTaiKhoan.setFocusPainted(false);
        btnTaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnTaiKhoan.setForeground(new java.awt.Color(238, 238, 238));
        btnTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiKhoanActionPerformed(evt);
            }
        });

        btnNhaXuatBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nxb.png"))); // NOI18N
        btnNhaXuatBan.setText("NHÀ XUẤT BẢN");
        btnNhaXuatBan.setBackground(new java.awt.Color(42, 71, 89));
        btnNhaXuatBan.setBorder(null);
        btnNhaXuatBan.setFocusPainted(false);
        btnNhaXuatBan.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnNhaXuatBan.setForeground(new java.awt.Color(238, 238, 238));
        btnNhaXuatBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhaXuatBanActionPerformed(evt);
            }
        });

        btnTacGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/author.png"))); // NOI18N
        btnTacGia.setText("TÁC GIẢ");
        btnTacGia.setBackground(new java.awt.Color(42, 71, 89));
        btnTacGia.setBorder(null);
        btnTacGia.setFocusPainted(false);
        btnTacGia.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnTacGia.setForeground(new java.awt.Color(238, 238, 238));
        btnTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTacGiaActionPerformed(evt);
            }
        });

        btnSuKien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/event.png"))); // NOI18N
        btnSuKien.setText("SỰ KIỆN");
        btnSuKien.setBackground(new java.awt.Color(42, 71, 89));
        btnSuKien.setBorder(null);
        btnSuKien.setFocusPainted(false);
        btnSuKien.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnSuKien.setForeground(new java.awt.Color(238, 238, 238));
        btnSuKien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuKienActionPerformed(evt);
            }
        });

        btnMuonPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/room.png"))); // NOI18N
        btnMuonPhong.setText("MƯỢN PHÒNG HỌC");
        btnMuonPhong.setBackground(new java.awt.Color(42, 71, 89));
        btnMuonPhong.setBorder(null);
        btnMuonPhong.setFocusPainted(false);
        btnMuonPhong.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnMuonPhong.setForeground(new java.awt.Color(238, 238, 238));
        btnMuonPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuonPhongActionPerformed(evt);
            }
        });

        btnTheLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/category.png"))); // NOI18N
        btnTheLoai.setText("THỂ LOẠI SÁCH");
        btnTheLoai.setBackground(new java.awt.Color(42, 71, 89));
        btnTheLoai.setBorder(null);
        btnTheLoai.setFocusPainted(false);
        btnTheLoai.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnTheLoai.setForeground(new java.awt.Color(238, 238, 238));
        btnTheLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTheLoaiActionPerformed(evt);
            }
        });

        btnPhieuTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phieuTra.png"))); // NOI18N
        btnPhieuTra.setText("PHIẾU TRẢ");
        btnPhieuTra.setBackground(new java.awt.Color(42, 71, 89));
        btnPhieuTra.setBorder(null);
        btnPhieuTra.setFocusPainted(false);
        btnPhieuTra.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnPhieuTra.setForeground(new java.awt.Color(238, 238, 238));
        btnPhieuTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhieuTraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayoutLayout = new javax.swing.GroupLayout(MenuLayout);
        MenuLayout.setLayout(MenuLayoutLayout);
        MenuLayoutLayout.setHorizontalGroup(
            MenuLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPhieuTra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTheLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnThongKe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSuKien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMuonPhong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
            .addComponent(btnNhaXuatBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTaiKhoan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTacGia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPhieuMuon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnHocSinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MenuLayoutLayout.setVerticalGroup(
            MenuLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayoutLayout.createSequentialGroup()
                .addComponent(btnSach, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPhieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHocSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSuKien, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMuonPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPhieuTra, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        panelLogo.setBackground(new java.awt.Color(42, 71, 89));
        panelLogo.setPreferredSize(new java.awt.Dimension(1366, 60));

        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library2.png"))); // NOI18N
        lblHome.setText("QUẢN LÝ THƯ VIỆN");
        lblHome.setBackground(new java.awt.Color(42, 71, 89));
        lblHome.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblHome.setForeground(new java.awt.Color(238, 238, 238));

        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/out2.png"))); // NOI18N
        btnLogOut.setBackground(new java.awt.Color(42, 71, 89));
        btnLogOut.setBorder(null);
        btnLogOut.setFocusPainted(false);
        btnLogOut.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(102, 153, 255));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menuIcon.png"))); // NOI18N

        javax.swing.GroupLayout panelLogoLayout = new javax.swing.GroupLayout(panelLogo);
        panelLogo.setLayout(panelLogoLayout);
        panelLogoLayout.setHorizontalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHome)
                .addGap(468, 468, 468)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelLogoLayout.setVerticalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(lblHome, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        panelContent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelContent.setMaximumSize(new java.awt.Dimension(1120, 666));
        panelContent.setMinimumSize(new java.awt.Dimension(1120, 666));
        panelContent.setPreferredSize(new java.awt.Dimension(1120, 666));
        panelContent.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MenuLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, 1139, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(panelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MenuLayout, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
                    .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnTheLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTheLoaiActionPerformed
        CardLayout cl = (CardLayout)(panelContent.getLayout());
        panelContent.setVisible(true);
        cl.show(panelContent, "theLoai");
        buttonColorHandler.changeButtonColor(btnTheLoai);
    }//GEN-LAST:event_btnTheLoaiActionPerformed

    private void btnMuonPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuonPhongActionPerformed
        //(TIENDAT2) TODO add your handling code here:
        CardLayout cl = (CardLayout) (panelContent.getLayout());
        panelContent.setVisible(true);
        cl.show(panelContent, "muonPhong");
        buttonColorHandler.changeButtonColor(btnMuonPhong);
    }//GEN-LAST:event_btnMuonPhongActionPerformed

    private void btnSuKienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuKienActionPerformed
        //(TIENDAT2) TODO add your handling code here:
        CardLayout cl = (CardLayout) (panelContent.getLayout());
        panelContent.setVisible(true);
        cl.show(panelContent, "suKien");
        buttonColorHandler.changeButtonColor(btnSuKien);
    }//GEN-LAST:event_btnSuKienActionPerformed

    private void btnTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTacGiaActionPerformed
        CardLayout cl = (CardLayout)(panelContent.getLayout());
        panelContent.setVisible(true);
        cl.show(panelContent, "tacGia");
        buttonColorHandler.changeButtonColor(btnTacGia);
    }//GEN-LAST:event_btnTacGiaActionPerformed

    private void btnNhaXuatBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhaXuatBanActionPerformed
        CardLayout cl = (CardLayout)(panelContent.getLayout());
        panelContent.setVisible(true);
        cl.show(panelContent, "nhaXuatBan");
        buttonColorHandler.changeButtonColor(btnNhaXuatBan);
    }//GEN-LAST:event_btnNhaXuatBanActionPerformed

    private void btnTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiKhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTaiKhoanActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnHocSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHocSinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHocSinhActionPerformed

    private void btnPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhieuMuonActionPerformed
        CardLayout cl = (CardLayout)(panelContent.getLayout());
        panelContent.setVisible(true);
        cl.show(panelContent, "phieuMuon");
        buttonColorHandler.changeButtonColor(btnPhieuMuon);
    }//GEN-LAST:event_btnPhieuMuonActionPerformed

    private void btnSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSachActionPerformed
        CardLayout cl = (CardLayout)(panelContent.getLayout());
        panelContent.setVisible(true);
        cl.show(panelContent, "sach");
        buttonColorHandler.changeButtonColor(btnSach);
    }//GEN-LAST:event_btnSachActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnPhieuTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhieuTraActionPerformed
        CardLayout cl = (CardLayout)(panelContent.getLayout());
        panelContent.setVisible(true);
        cl.show(panelContent, "phieuTra");
        buttonColorHandler.changeButtonColor(btnPhieuTra);
    }//GEN-LAST:event_btnPhieuTraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        SwingUtilities.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuLayout;
    private javax.swing.JButton btnHocSinh;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnMuonPhong;
    private javax.swing.JButton btnNhaXuatBan;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnPhieuMuon;
    private javax.swing.JButton btnPhieuTra;
    private javax.swing.JButton btnSach;
    private javax.swing.JButton btnSuKien;
    private javax.swing.JButton btnTacGia;
    private javax.swing.JButton btnTaiKhoan;
    private javax.swing.JButton btnTheLoai;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblHome;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelLogo;
    // End of variables declaration//GEN-END:variables
}
