
package View.ChucNang;


import Model.DAO.DocGiaDAO;
import Model.DAO.MuonPhongDAO;
import Model.MuonPhong;

import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Cell;

import Model.PhongHoc;
import Model.DAO.PhongHocDAO;
import Model.DocGia;
import java.awt.Component;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.SQLException;
import java.time.LocalDateTime;

import java.util.List;
import javax.swing.JOptionPane;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Asus
 */
public class PanelMuonPhong extends javax.swing.JPanel {

    
        private final MuonPhongDAO muonPhongDAO = new MuonPhongDAO();
        private final PhongHocDAO phongHocDAO = new PhongHocDAO();
    /**
     * Creates new form MuonPhong
     */
    public PanelMuonPhong() {
        initComponents();
        loadComboBoxes();
        loadTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbPhong = new javax.swing.JComboBox<PhongHoc>();
        jLabel2 = new javax.swing.JLabel();
        txtMaDocGia = new javax.swing.JTextField();
        btnKiemTra = new javax.swing.JButton();
        lblTenDocGia = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        dtpTGmuon = new com.github.lgooddatepicker.components.DateTimePicker();
        jLabel5 = new javax.swing.JLabel();
        dtpTGtra = new com.github.lgooddatepicker.components.DateTimePicker();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaGhiChu = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        btnNhap = new javax.swing.JButton();
        btnXuat = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableMuonPhong = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(1120, 666));
        setMinimumSize(new java.awt.Dimension(1120, 666));
        setPreferredSize(new java.awt.Dimension(1120, 666));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Tên phòng");
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jLabel2.setText("Mã độc giả");
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        txtMaDocGia.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        btnKiemTra.setText("Kiểm tra");
        btnKiemTra.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnKiemTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKiemTraActionPerformed(evt);
            }
        });

        lblTenDocGia.setText("Tên của độc giả ?");
        lblTenDocGia.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblTenDocGia.setForeground(new java.awt.Color(51, 255, 51));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thời gian mượn/trả", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 13))); // NOI18N

        jLabel4.setText("Thời gian mượn");
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jLabel5.setText("Thời gian trả");
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(dtpTGmuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dtpTGtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dtpTGmuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dtpTGtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jLabel6.setText("Ghi chú");
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        txaGhiChu.setColumns(20);
        txaGhiChu.setRows(5);
        jScrollPane1.setViewportView(txaGhiChu);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnNhap.setText("Nhập dữ liệu");
        btnNhap.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnNhap.setToolTipText("");
        btnNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapActionPerformed(evt);
            }
        });

        btnXuat.setText("Xuất dữ liệu");
        btnXuat.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 13))); // NOI18N

        btnThem.setText("Thêm phiếu mượn");
        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa phiếu mượn");
        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa phiếu mượn");
        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNhap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXuat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTenDocGia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnReset)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnKiemTra)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtMaDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKiemTra))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTenDocGia)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReset)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(653, 653, 653))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableMuonPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phiếu mượn", "Tên Phòng", "Tên độc giả ", "Thời gian mượn", "Thời gian trả", "Ghi chú"
            }
        ));
        tableMuonPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMuonPhongMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableMuonPhong);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 87, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableMuonPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMuonPhongMouseClicked
        // TODO add your handling code here:
        int row = tableMuonPhong.getSelectedRow();
                if (row >= 0) {
                    int maphong = Integer.parseInt(tableMuonPhong.getValueAt(row, 1).toString());
                    lblTenDocGia.setText(tableMuonPhong.getValueAt(row, 2).toString());
                    txaGhiChu.setText(tableMuonPhong.getValueAt(row, 5).toString());
                    
                    for (int i = 0; i < cbPhong.getItemCount(); i++) {
                    if (cbPhong.getItemAt(i).getMaphong() == maphong) {
                        cbPhong.setSelectedIndex(i);
                        break;
                    }
                }
                }
    }//GEN-LAST:event_tableMuonPhongMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        addMuonPhong();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnKiemTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKiemTraActionPerformed
        // TODO add your handling code here:
            try {
                String input = txtMaDocGia.getText().trim();
                if (input.isEmpty()) {
                    lblTenDocGia.setText("Vui lòng nhập mã độc giả.");
                    return;
                }

                int madocgia = Integer.parseInt(input);

                DocGiaDAO docGiaDAO = new DocGiaDAO();
                DocGia docGia = docGiaDAO.getDocGiaById(madocgia);

                if (docGia != null) {
                    lblTenDocGia.setText(docGia.getTendocgia());
                } else {
                    lblTenDocGia.setText("Không tìm thấy độc giả.");
                }

            } catch (NumberFormatException ex) {
                lblTenDocGia.setText("Mã độc giả không hợp lệ.");
            }catch (SQLException ex) {
                lblTenDocGia.setText("Lỗi kết nối CSDL: " + ex.getMessage());
            }
    }//GEN-LAST:event_btnKiemTraActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        updateMuonPhong();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        deleteMuonPhong();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        searchTheoTenDocGia();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtTimKiem.setText("");
        loadTableData();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Chọn nơi lưu file Excel");
        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            if (!fileToSave.getAbsolutePath().endsWith(".xlsx")) {
                fileToSave = new File(fileToSave.getAbsolutePath() + ".xlsx");
            }

            try (Workbook workbook = new XSSFWorkbook()) {
                Sheet sheet = workbook.createSheet("PhieuMuonPhong");
                DefaultTableModel model = (DefaultTableModel) tableMuonPhong.getModel();

                // Ghi header
                Row header = sheet.createRow(0);
                for (int i = 0; i < model.getColumnCount(); i++) {
                    Cell cell = header.createCell(i);
                    cell.setCellValue(model.getColumnName(i));
                }

                // Ghi dữ liệu
                for (int i = 0; i < model.getRowCount(); i++) {
                    Row row = sheet.createRow(i + 1);
                    for (int j = 0; j < model.getColumnCount(); j++) {
                        Object value = model.getValueAt(i, j);
                        row.createCell(j).setCellValue(value != null ? value.toString() : "");
                    }
                }

                try (FileOutputStream fos = new FileOutputStream(fileToSave)) {
                    workbook.write(fos);
                    JOptionPane.showMessageDialog(this, "Xuất file Excel thành công: " + fileToSave.getAbsolutePath());
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Lỗi khi xuất Excel: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnXuatActionPerformed

    private void btnNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapActionPerformed
        // TODO add your handling code here:
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Chọn file Excel để nhập");
            int userSelection = fileChooser.showOpenDialog(this);

            if (userSelection == JFileChooser.APPROVE_OPTION) {
                File file = fileChooser.getSelectedFile();

                try (Workbook workbook = new XSSFWorkbook(file)) {
                    Sheet sheet = workbook.getSheetAt(0);
                    int successCount = 0, errorCount = 0;
                    StringBuilder errorLog = new StringBuilder();

                    boolean skipHeader = true;
                    for (Row row : sheet) {
                        if (skipHeader) {
                            skipHeader = false;
                            continue;
                        }

                        try {
                            String tenPhong = row.getCell(0).toString().trim();
                            String tenDocGia = row.getCell(1).toString().trim();
                            String tgMuonStr = row.getCell(2).toString().trim();
                            String tgTraStr = row.getCell(3).toString().trim();
                            String ghiChu = row.getCell(4) != null ? row.getCell(4).toString().trim() : "";

                            PhongHocDAO phongDAO = new PhongHocDAO();
                            DocGiaDAO docGiaDAO = new DocGiaDAO();

                            PhongHoc phong = phongDAO.findByTenPhong(tenPhong);
                            DocGia docGia = docGiaDAO.getDocGiaByTen(tenDocGia);

                            if (phong == null) throw new Exception("Không tìm thấy phòng: " + tenPhong);
                            if (docGia == null) throw new Exception("Không tìm thấy độc giả: " + tenDocGia);

                            LocalDateTime tgMuon = LocalDateTime.parse(tgMuonStr, DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm"));
                            LocalDateTime tgTra = LocalDateTime.parse(tgTraStr, DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm"));

                            if (tgMuon.isAfter(tgTra)) throw new Exception("Thời gian mượn lớn hơn thời gian trả");

                            MuonPhong mp = new MuonPhong();
                            mp.setMaphong(phong.getMaphong());
                            mp.setMadocgia(docGia.getMadocgia());
                            mp.setTgianmuon(tgMuon);
                            mp.setTgiantra(tgTra);
                            mp.setGhichu(ghiChu);

                            if (muonPhongDAO.addMuonPhong(mp)) {
                                successCount++;
                            } else {
                                throw new Exception("Không thể thêm vào CSDL");
                            }
                        } catch (Exception exRow) {
                            errorCount++;
                            errorLog.append("Dòng ").append(row.getRowNum() + 1).append(": ")
                                    .append(exRow.getMessage()).append("\n");
                            exRow.printStackTrace();
                        }
                    }

                    loadTableData();
                    JOptionPane.showMessageDialog(this,
                        "Đã nhập: " + successCount + " dòng, lỗi: " + errorCount +
                        (errorCount > 0 ? "\n\nChi tiết:\n" + errorLog.toString() : "")
                    );
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Lỗi khi đọc file Excel: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            }
    }//GEN-LAST:event_btnNhapActionPerformed


    
    private void loadComboBoxes() {
        try{
        // Tải Nhà Xuất Bản
        List<PhongHoc> phonghocList = phongHocDAO.getAllPhongHoc();
        for (PhongHoc phonghoc : phonghocList) {
            cbPhong.addItem(phonghoc);
        }
        cbPhong.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof PhongHoc) {
                    PhongHoc phonghoc = (PhongHoc) value;
                    setText(phonghoc.getTenphong());
                }
                return this;
            }
        });
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu ComboBox: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    private void loadTableData() {
        try {
            List<Object[]> mpList = muonPhongDAO.getAllMuonPhongWithDetails();
            DefaultTableModel model = (DefaultTableModel) tableMuonPhong.getModel();
            model.setRowCount(0); // Xóa dữ liệu cũ

            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm");

            for (Object[] row : mpList) {
                int maPhieu = (int) row[0];
                String tenPhong = (String) row[1];
                String tenDocGia = (String) row[2];
                LocalDateTime tgMuon = (LocalDateTime) row[3];
                LocalDateTime tgTra = (LocalDateTime) row[4];
                String ghiChu = (String) row[5];

                model.addRow(new Object[]{
                    maPhieu,
                    tenPhong,
                    tenDocGia,
                    tgMuon != null ? tgMuon.format(formatter) : "",
                    tgTra != null ? tgTra.format(formatter) : "",
                    ghiChu
                });
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
     
    
    private void addMuonPhong() {
        try {
            // Tạo đối tượng MuonPhong
            MuonPhong muonPhong = new MuonPhong();

            // Lấy phòng học được chọn từ combo box
            PhongHoc selectedPhong = (PhongHoc) cbPhong.getSelectedItem();
            if (selectedPhong == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn phòng học!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            muonPhong.setMaphong(selectedPhong.getMaphong());

            // Lấy mã độc giả từ lblTenDocGia (phải kiểm tra mã đã được nhập trước đó)
            String inputMaDocGia = txtMaDocGia.getText().trim();
            if (inputMaDocGia.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập mã độc giả trước khi thêm phiếu mượn!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            int madocgia = Integer.parseInt(inputMaDocGia);
            muonPhong.setMadocgia(madocgia);

            // Lấy thời gian mượn và trả từ DateTimePicker
            LocalDateTime tgMuon = dtpTGmuon.getDateTimeStrict();
            LocalDateTime tgTra = dtpTGtra.getDateTimeStrict();
            if (tgMuon == null || tgTra == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn đầy đủ thời gian mượn và trả!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            //tgian muon ko được lớn hơn tgian trả
            if (tgMuon.isAfter(tgTra)) {
            JOptionPane.showMessageDialog(this, "Thời gian mượn phải nhỏ hơn thời gian trả!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
            }
            muonPhong.setTgianmuon(tgMuon);
            muonPhong.setTgiantra(tgTra);

            // Lấy ghi chú từ TextArea
            String ghichu = txaGhiChu.getText().trim();
            muonPhong.setGhichu(ghichu);

            // Thêm phiếu mượn vào CSDL
            if (muonPhongDAO.addMuonPhong(muonPhong)) {
                JOptionPane.showMessageDialog(this, "Thêm phiếu mượn phòng thành công!");
                loadTableData();
                clearFields();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm phiếu mượn phòng thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Mã độc giả không hợp lệ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi thêm phiếu mượn phòng: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    
    private void updateMuonPhong() {
        int row = tableMuonPhong.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một phiếu mượn phòng để sửa!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // Tạo đối tượng MuonPhong
            MuonPhong muonPhong = new MuonPhong();
            muonPhong.setMaphieump(Integer.parseInt(tableMuonPhong.getValueAt(row, 0).toString()));
            muonPhong.setGhichu(txaGhiChu.getText().trim());

            // Lấy ngày và giờ từ DatePicker và TimePicker
            LocalDateTime tgMuon = dtpTGmuon.getDateTimeStrict();
            LocalDateTime tgTra = dtpTGtra.getDateTimeStrict();

            // Kiểm tra dữ liệu đầu vào
            if (tgMuon == null || tgTra == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn đầy đủ thời gian mượn và trả!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            //tgian muon ko được lớn hơn tgian trả
            if (tgMuon.isAfter(tgTra)) {
            JOptionPane.showMessageDialog(this, "Thời gian mượn phải nhỏ hơn thời gian trả!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
            }
            
            muonPhong.setTgianmuon(tgMuon);
            muonPhong.setTgiantra(tgTra);
            
            // Lấy mã độc giả từ txtMaDocGia
            String inputMaDocGia = txtMaDocGia.getText().trim();
            if (inputMaDocGia.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập mã độc giả!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            int madocgia = Integer.parseInt(inputMaDocGia);
            muonPhong.setMadocgia(madocgia);
            

            // Kiểm tra Phòng Học được chọn
            PhongHoc selectedPhongHoc = (PhongHoc) cbPhong.getSelectedItem();
            if (selectedPhongHoc == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn một Phòng học!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Gán maphieump từ nhà xuất bản được chọn
            muonPhong.setMaphong(selectedPhongHoc.getMaphong());

            if (muonPhongDAO.updateMuonPhong(muonPhong)) {
                JOptionPane.showMessageDialog(this, "Sửa Phiếu mượn phòng thành công!");
                loadTableData();
                clearFields();
            } else {
                JOptionPane.showMessageDialog(this, "Sửa Phiếu mượn phòng thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số hợp lệ", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi sửa phiếu mượn phòng: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    
    private void deleteMuonPhong() {
        int row = tableMuonPhong.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một phiếu mượn phòng để xóa!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa phiếu mượn phòng này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                int maphieump = Integer.parseInt(tableMuonPhong.getValueAt(row, 0).toString());
                if (muonPhongDAO.deleteMuonPhong(maphieump)) {
                    JOptionPane.showMessageDialog(this, "Xóa phiếu mượn phòng thành công!");
                    loadTableData();
                    clearFields();
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa phiếu mượn phòng thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Lỗi khi xóa phiếu mượn phòng: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    // Tìm kiếm phiếu mượn theo tên độc giả (Sửa tìm kiếm)
    private void searchTheoTenDocGia() {
    String keyword = txtTimKiem.getText().trim().toLowerCase();
        if (keyword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên độc giả cần tìm!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            List<Object[]> mpList = muonPhongDAO.getAllMuonPhongWithDetails();
            DefaultTableModel model = (DefaultTableModel) tableMuonPhong.getModel();
            model.setRowCount(0);

            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm");

            for (Object[] row : mpList) {
                int maphieu = (int) row[0];
                String tenPhong = (String) row[1];
                String tenDocGia = (String) row[2];
                LocalDateTime tgMuon = (LocalDateTime) row[3];
                LocalDateTime tgTra = (LocalDateTime) row[4];
                String ghiChu = (String) row[5];

                if (!tenDocGia.toLowerCase().contains(keyword)) continue;

                model.addRow(new Object[]{
                    maphieu,
                    tenPhong,
                    tenDocGia,
                    tgMuon != null ? tgMuon.format(formatter) : "",
                    tgTra != null ? tgTra.format(formatter) : "",
                    ghiChu
                });
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tìm kiếm: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }


    
    private void clearFields() {
        txtMaDocGia.setText("");
        txaGhiChu.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKiemTra;
    private javax.swing.JButton btnNhap;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuat;
    private javax.swing.JComboBox<PhongHoc> cbPhong;
    private com.github.lgooddatepicker.components.DateTimePicker dtpTGmuon;
    private com.github.lgooddatepicker.components.DateTimePicker dtpTGtra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTenDocGia;
    private javax.swing.JTable tableMuonPhong;
    private javax.swing.JTextArea txaGhiChu;
    private javax.swing.JTextField txtMaDocGia;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
