/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.ChucNang;
import Control.DocGiaDAO;
import Control.NhanVienDAO;
import Control.PhieuTraDAO;
import Control.SachDAO;
import Control.PhieuMuonDAO;
import Model.DocGia;
import Model.NhanVien;
import Model.PhieuMuon;
import Model.PhieuTra;
import Model.Sach;
import View.Menu;
import java.awt.event.ActionEvent;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author TUF
 */
public class PanelPhieuTra extends javax.swing.JPanel {
private PhieuTraDAO phieuTraDAO = new PhieuTraDAO();
    private DocGiaDAO docGiaDAO = new DocGiaDAO();
    private NhanVienDAO nhanVienDAO = new NhanVienDAO();
    private PhieuMuonDAO phieuMuonDAO = new PhieuMuonDAO();
    private SachDAO sachDAO = new SachDAO();
    private PhieuMuon selectedPhieuMuon;
    /**
     * Creates new form PhieuTra
     */
    public PanelPhieuTra() {
        initComponents();
        loadTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tblMaphieu1 = new javax.swing.JLabel();
        txtMaphieu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        date = new com.github.lgooddatepicker.components.DateTimePicker();
        tblMaphieu2 = new javax.swing.JLabel();
        btnKiemtra = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblghichu = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        btntrasach = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1120, 666));
        setMinimumSize(new java.awt.Dimension(1120, 666));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phiếu trả", "Mã phiếu", "Tên độc giả", "Tên nhân viên", "Tên sách", "Ngày mượn", "Ngày hẹn trả", "Ngày trả", "Phí phạt", "Ghi chú"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        tblMaphieu1.setText("Mã phiếu");

        jLabel2.setText("Ngày trả : ");

        tblMaphieu2.setText("Mã phiếu :");

        btnKiemtra.setText("KIỂM TRA");
        btnKiemtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKiemtraActionPerformed(evt);
            }
        });

        tblghichu.setColumns(20);
        tblghichu.setRows(5);
        jScrollPane2.setViewportView(tblghichu);

        jLabel4.setText("Ghi chú :");

        btntrasach.setText("Trả sách");
        btntrasach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntrasachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1120, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btntrasach))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tblMaphieu1)
                            .addComponent(jLabel2))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tblMaphieu2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMaphieu, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnKiemtra))
                            .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tblMaphieu1)
                    .addComponent(txtMaphieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKiemtra))
                .addGap(18, 18, 18)
                .addComponent(tblMaphieu2)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntrasach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnKiemtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKiemtraActionPerformed
    try {
            int maphieu = Integer.parseInt(txtMaphieu.getText().trim());
            PhieuMuon pm = phieuTraDAO.getPhieuMuonById(maphieu);
            if (pm != null) {
                selectedPhieuMuon = pm;
                tblMaphieu2.setText("Đang mượn");
            } else {
                selectedPhieuMuon = null;
                tblMaphieu2.setText("Không tồn tại");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Mã phiếu phải là số!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            tblMaphieu2.setText("");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi kiểm tra: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            tblMaphieu2.setText("");
        }
    }//GEN-LAST:event_btnKiemtraActionPerformed

    private void btntrasachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntrasachActionPerformed
if (selectedPhieuMuon == null) {
        JOptionPane.showMessageDialog(this, "Vui lòng kiểm tra mã phiếu mượn trước!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        return;
    }

    LocalDateTime ngaytra = date.getDateTimePermissive();
    if (ngaytra == null) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày trả!", "Lỗi", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn trả sách này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        try {
            // Tính phí phạt
            long daysLate = ChronoUnit.DAYS.between(selectedPhieuMuon.getNgaytra().toLocalDate(), ngaytra.toLocalDate());
            double phiphat = daysLate > 0 ? daysLate * 10000 : 0; // 10,000 VNĐ/ngày trễ

            // Tạo phiếu trả
            PhieuTra pt = new PhieuTra(
                0, // maphieutra sẽ tự tăng
                selectedPhieuMuon.getMaphieu(),
                selectedPhieuMuon.getMadocgia(),
                selectedPhieuMuon.getManv(),
                selectedPhieuMuon.getMasach(),
                selectedPhieuMuon.getNgaymuon(),
                selectedPhieuMuon.getNgaytra(),
                ngaytra,
                phiphat,
                tblghichu.getText().trim()
            );

            // Lưu phiếu trả và cập nhật trạng thái phiếu mượn thành "Đã trả"
            if (phieuTraDAO.addPhieuTra(pt) && phieuMuonDAO.returnBook(selectedPhieuMuon.getMaphieu())) {
                JOptionPane.showMessageDialog(this, "Trả sách thành công! Phí phạt: " + phiphat + " VNĐ");
                loadTableData(); // Làm mới bảng trong PanelPhieuTra
                clearFields();

                // Làm mới bảng trong PanelPhieuMuon
                Menu menu = (Menu) SwingUtilities.getWindowAncestor(this); // Lấy frame cha (Menu)
                if (menu != null) {
                    PanelPhieuMuon panelPhieuMuon = menu.getPanelPhieuMuon();
                    if (panelPhieuMuon != null) {
                        panelPhieuMuon.refreshTableData(); // Gọi làm mới
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Trả sách thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi trả sách: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btntrasachActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKiemtra;
    private javax.swing.JButton btntrasach;
    private com.github.lgooddatepicker.components.DateTimePicker date;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel tblMaphieu1;
    private javax.swing.JLabel tblMaphieu2;
    private javax.swing.JTextArea tblghichu;
    private javax.swing.JTextField txtMaphieu;
    // End of variables declaration//GEN-END:variables

    private void loadTableData() {
        try {
            List<PhieuTra> phieuTraList = phieuTraDAO.getAllPhieuTra();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            for (PhieuTra pt : phieuTraList) {
                // Lấy tên độc giả, nhân viên, sách (giả sử có các phương thức getTen)
                String tendocgia = getTenDocGia(pt.getMadocgia());
                String tennv = getTenNhanVien(pt.getManv());
                String tensach = getTenSach(pt.getMasach());
                model.addRow(new Object[]{
                    pt.getMaphieutra(),
                    pt.getMaphieu(),
                    tendocgia != null ? tendocgia : "Không xác định",
                    tennv != null ? tennv : "Không xác định",
                    tensach != null ? tensach : "Không xác định",
                    pt.getNgaymuon(),
                    pt.getNgayhentra(),
                    pt.getNgaytra(),
                    pt.getPhiphat(),
                    pt.getGhichu()
                });
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu phiếu trả: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void clearFields() {
        txtMaphieu.setText("");
        tblMaphieu2.setText("");
        date.clear();
        tblghichu.setText("");
        selectedPhieuMuon = null;
    }

    private String getTenDocGia(int madocgia) throws SQLException {
        DocGia docGia = docGiaDAO.getDocGiaById(madocgia);
        return docGia != null ? docGia.getTendocgia() : null;
    }

    private String getTenNhanVien(int manv) throws SQLException {
        NhanVien nv = nhanVienDAO.getNhanVienById(manv);
        return nv != null ? nv.getTennv() : null;
    }

    private String getTenSach(int masach) throws SQLException {
        Sach sach = sachDAO.getSachById(masach);
        return sach != null ? sach.getTensach() : null;
    }
}
