/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.ChucNang;

import UI.BasePanel;
import Model.DAO.SachDAO;
import Model.DAO.TacGiaDAO;
import Model.DAO.NhaXuatBanDAO;
import Model.DAO.TheLoaiDAO;
import Model.Sach;
import Model.TacGia;
import Model.NhaXuatBan;
import Model.TheLoai;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.sql.SQLException;
import java.util.List;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;

public class PanelSach extends BasePanel {

    private final SachDAO sachDAO = new SachDAO();
    private final TacGiaDAO tacGiaDAO = new TacGiaDAO();
    private final NhaXuatBanDAO nxbDAO = new NhaXuatBanDAO();
    private final TheLoaiDAO theLoaiDAO = new TheLoaiDAO();
    
    public PanelSach() {
        initComponents();
        loadComboBoxes();
        loadTableData();
        styleButton(btnThem);
        styleButton(btnSua);
        styleButton(btnXoa);
        styleButton(btnNhapDuLieu);
        styleButton(btnXuatDuLieu);
        styleTable(tableSach);
            txtTimKiem.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) { searchSach(); }
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) { searchSach(); }
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) { searchSach(); }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInfor = new javax.swing.JPanel();
        TenSach = new javax.swing.JLabel();
        txtTenSach = new javax.swing.JTextField();
        NXB = new javax.swing.JLabel();
        NamXuatBan = new javax.swing.JLabel();
        txtNamXB = new javax.swing.JTextField();
        cbNXB = new javax.swing.JComboBox<>();
        TacGia = new javax.swing.JLabel();
        cbTacGia = new javax.swing.JComboBox<>();
        TheLoai = new javax.swing.JLabel();
        cbTheLoai = new javax.swing.JComboBox<>();
        SoTrang = new javax.swing.JLabel();
        txtSoTrang = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        NamXuatBan1 = new javax.swing.JLabel();
        MaSach = new javax.swing.JLabel();
        txtMaSach = new javax.swing.JTextField();
        panelButton = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        TimKiem = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        cbTimKiem = new javax.swing.JComboBox<>();
        panelTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSach = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnNhapDuLieu = new javax.swing.JButton();
        btnXuatDuLieu = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1120, 666));
        setMinimumSize(new java.awt.Dimension(1120, 666));
        setPreferredSize(new java.awt.Dimension(1120, 666));

        panelInfor.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        TenSach.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        TenSach.setText("Tên Sách");

        txtTenSach.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtTenSach.setPreferredSize(new java.awt.Dimension(64, 25));

        NXB.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        NXB.setText("NXB");

        NamXuatBan.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        NamXuatBan.setText("Năm XB");

        txtNamXB.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtNamXB.setPreferredSize(new java.awt.Dimension(64, 25));

        cbNXB.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        TacGia.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        TacGia.setText("Tác Giả");

        cbTacGia.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cbTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTacGiaActionPerformed(evt);
            }
        });

        TheLoai.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        TheLoai.setText("Thể loại");

        cbTheLoai.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        SoTrang.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        SoTrang.setText("Số trang");

        txtSoTrang.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtSoTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoTrangActionPerformed(evt);
            }
        });

        txtSoLuong.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        NamXuatBan1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        NamXuatBan1.setText("Số lượng");

        MaSach.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        MaSach.setText("Mã sách");

        txtMaSach.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtMaSach.setPreferredSize(new java.awt.Dimension(64, 25));

        javax.swing.GroupLayout panelInforLayout = new javax.swing.GroupLayout(panelInfor);
        panelInfor.setLayout(panelInforLayout);
        panelInforLayout.setHorizontalGroup(
            panelInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInforLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInforLayout.createSequentialGroup()
                        .addComponent(NamXuatBan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNamXB, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInforLayout.createSequentialGroup()
                        .addComponent(NamXuatBan1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInforLayout.createSequentialGroup()
                        .addComponent(MaSach)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(114, 114, 114)
                .addGroup(panelInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInforLayout.createSequentialGroup()
                        .addComponent(TenSach)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInforLayout.createSequentialGroup()
                        .addGroup(panelInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInforLayout.createSequentialGroup()
                                .addComponent(SoTrang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSoTrang)
                                .addGap(34, 34, 34))
                            .addGroup(panelInforLayout.createSequentialGroup()
                                .addComponent(TacGia)
                                .addGap(18, 18, 18)
                                .addComponent(cbTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(81, 81, 81)))
                .addGap(52, 52, 52)
                .addGroup(panelInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelInforLayout.createSequentialGroup()
                        .addComponent(NXB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInforLayout.createSequentialGroup()
                        .addComponent(TheLoai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelInforLayout.setVerticalGroup(
            panelInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInforLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelInforLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NamXuatBan)
                            .addComponent(txtNamXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NamXuatBan1)))
                    .addGroup(panelInforLayout.createSequentialGroup()
                        .addGroup(panelInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInforLayout.createSequentialGroup()
                                .addGroup(panelInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TenSach)
                                    .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MaSach)
                                    .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TacGia)
                                    .addComponent(cbTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelInforLayout.createSequentialGroup()
                                .addGap(0, 5, Short.MAX_VALUE)
                                .addGroup(panelInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NXB)
                                    .addComponent(cbNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TheLoai)
                                    .addComponent(cbTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SoTrang)
                            .addComponent(txtSoTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        panelButton.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));
        panelButton.setPreferredSize(new java.awt.Dimension(1120, 86));

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        TimKiem.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        TimKiem.setText("Tìm Kiếm:");

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });

        cbTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã sách", "Tên sách", "Tác giả", "NXB", "Thể loại" }));

        javax.swing.GroupLayout panelButtonLayout = new javax.swing.GroupLayout(panelButton);
        panelButton.setLayout(panelButtonLayout);
        panelButtonLayout.setHorizontalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(TimKiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTimKiem, 0, 141, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        panelButtonLayout.setVerticalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TimKiem))
                    .addGroup(panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        tableSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Tác giả", "NXB", "Thể loại", "Năm XB", "Số trang", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableSach.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tableSach.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableSach);
        if (tableSach.getColumnModel().getColumnCount() > 0) {
            tableSach.getColumnModel().getColumn(0).setResizable(false);
            tableSach.getColumnModel().getColumn(0).setPreferredWidth(10);
            tableSach.getColumnModel().getColumn(1).setResizable(false);
            tableSach.getColumnModel().getColumn(1).setPreferredWidth(160);
            tableSach.getColumnModel().getColumn(2).setResizable(false);
            tableSach.getColumnModel().getColumn(2).setPreferredWidth(80);
            tableSach.getColumnModel().getColumn(3).setResizable(false);
            tableSach.getColumnModel().getColumn(4).setResizable(false);
            tableSach.getColumnModel().getColumn(4).setPreferredWidth(30);
            tableSach.getColumnModel().getColumn(5).setResizable(false);
            tableSach.getColumnModel().getColumn(5).setPreferredWidth(20);
            tableSach.getColumnModel().getColumn(6).setResizable(false);
            tableSach.getColumnModel().getColumn(6).setPreferredWidth(20);
            tableSach.getColumnModel().getColumn(7).setResizable(false);
            tableSach.getColumnModel().getColumn(7).setPreferredWidth(20);
        }

        javax.swing.GroupLayout panelTableLayout = new javax.swing.GroupLayout(panelTable);
        panelTable.setLayout(panelTableLayout);
        panelTableLayout.setHorizontalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        panelTableLayout.setVerticalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTableLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnNhapDuLieu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNhapDuLieu.setText("Nhập dữ liệu");
        btnNhapDuLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapDuLieuActionPerformed(evt);
            }
        });

        btnXuatDuLieu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXuatDuLieu.setText("Xuất dữ liệu");
        btnXuatDuLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatDuLieuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnXuatDuLieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNhapDuLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnNhapDuLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXuatDuLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelInfor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 1107, Short.MAX_VALUE))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelInfor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTable, javax.swing.GroupLayout.PREFERRED_SIZE, 429, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTacGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTacGiaActionPerformed

    private void txtSoTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoTrangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoTrangActionPerformed

    private void tableSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSachMouseClicked
    int row = tableSach.getSelectedRow();
        if (row >= 0) {
            try {
            // Lấy dữ liệu từ bảng
            txtMaSach.setText(tableSach.getValueAt(row, 0).toString()); // Thêm dòng này để hiển thị masach
            txtTenSach.setText(tableSach.getValueAt(row, 1).toString());
            txtNamXB.setText(tableSach.getValueAt(row, 5).toString());
            txtSoTrang.setText(tableSach.getValueAt(row, 6).toString());
            txtSoLuong.setText(tableSach.getValueAt(row, 7).toString());

            // Lấy mã số từ dữ liệu bảng (cột 2, 3, 4 chứa tên, không chứa mã trực tiếp)
            int matacgia = -1;
            int manxb = -1;
            int matheloai = -1;

            // Tìm mã số dựa trên tên trong bảng (cột 2, 3, 4)
            String tenTacGia = tableSach.getValueAt(row, 2).toString();
            String tenNXB = tableSach.getValueAt(row, 3).toString();
            String tenTheLoai = tableSach.getValueAt(row, 4).toString();

            // Tìm mã số trong danh sách combo box dựa trên tên
            for (int i = 0; i < cbTacGia.getItemCount(); i++) {
                TacGia tacGia = cbTacGia.getItemAt(i);
                if (tacGia.getTentacgia().equals(tenTacGia)) {
                    matacgia = tacGia.getMatacgia();
                    cbTacGia.setSelectedIndex(i);
                    break;
                }
            }
            for (int i = 0; i < cbNXB.getItemCount(); i++) {
                NhaXuatBan nxb = cbNXB.getItemAt(i);
                if (nxb.getTennxb().equals(tenNXB)) {
                    manxb = nxb.getManxb();
                    cbNXB.setSelectedIndex(i);
                    break;
                }
            }
            for (int i = 0; i < cbTheLoai.getItemCount(); i++) {
                TheLoai theLoai = cbTheLoai.getItemAt(i);
                if (theLoai.getTentheloai().equals(tenTheLoai)) {
                    matheloai = theLoai.getMatheloai();
                    cbTheLoai.setSelectedIndex(i);
                    break;
                }
            }

            // Nếu không tìm thấy, đặt về mục đầu tiên hoặc giữ nguyên
            if (matacgia == -1) cbTacGia.setSelectedIndex(0);
            if (manxb == -1) cbNXB.setSelectedIndex(0);
            if (matheloai == -1) cbTheLoai.setSelectedIndex(0);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi chọn sách: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_tableSachMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        addSach();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        updateSach();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        deleteSach();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed

    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void btnXuatDuLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatDuLieuActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Chọn nơi lưu file Excel");
        fileChooser.setSelectedFile(new File("danh_sach_sach.xlsx"));
        fileChooser.setFileFilter(new javax.swing.filechooser.FileFilter() {
            @Override
            public boolean accept(File f) {
                return f.isDirectory() || f.getName().toLowerCase().endsWith(".xlsx");
            }

            @Override
            public String getDescription() {
                return "Excel Files (*.xlsx)";
            }
        });

        int result = fileChooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            // Đảm bảo file có đuôi .xlsx
            String filePath = selectedFile.getAbsolutePath();
            if (!filePath.toLowerCase().endsWith(".xlsx")) {
                filePath += ".xlsx";
                selectedFile = new File(filePath);
            }

            try (Workbook workbook = new XSSFWorkbook()) {
                Sheet sheet = workbook.createSheet("DanhSachSach");

                // Tạo dòng tiêu đề
                Row headerRow = sheet.createRow(0);
                String[] headers = new String[]{"Mã sách", "Tên sách", "Tác giả", "NXB", "Thể loại", "Năm XB", "Số trang", "Số lượng"};
                for (int i = 0; i < headers.length; i++) {
                    Cell cell = headerRow.createCell(i);
                    cell.setCellValue(headers[i]);
                }

                // Ghi dữ liệu từ bảng
                DefaultTableModel model = (DefaultTableModel) tableSach.getModel();
                for (int i = 0; i < model.getRowCount(); i++) {
                    Row row = sheet.createRow(i + 1);
                    row.createCell(0).setCellValue((String) model.getValueAt(i, 0));
                    row.createCell(1).setCellValue((String) model.getValueAt(i, 1)); // Tên sách
                    row.createCell(2).setCellValue((String) model.getValueAt(i, 2)); // Tác giả
                    row.createCell(3).setCellValue((String) model.getValueAt(i, 3)); // NXB
                    row.createCell(4).setCellValue((String) model.getValueAt(i, 4)); // Thể loại
                    row.createCell(5).setCellValue((int) model.getValueAt(i, 5)); // Năm XB
                    row.createCell(6).setCellValue((int) model.getValueAt(i, 6)); // Số trang
                    row.createCell(7).setCellValue((int) model.getValueAt(i, 7)); // Số lượng
                }

                // Tự động điều chỉnh độ rộng cột
                for (int i = 0; i < headers.length; i++) {
                    sheet.autoSizeColumn(i);
                }

                // Ghi file
                try (FileOutputStream fileOut = new FileOutputStream(selectedFile)) {
                    workbook.write(fileOut);
                }

                JOptionPane.showMessageDialog(this, "Xuất dữ liệu thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Lỗi khi xuất file Excel: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnXuatDuLieuActionPerformed

    private void btnNhapDuLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapDuLieuActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Chọn file Excel để nhập dữ liệu sách");
        fileChooser.setFileFilter(new javax.swing.filechooser.FileFilter() {
            @Override
            public boolean accept(File f) {
                return f.isDirectory() || f.getName().toLowerCase().endsWith(".xlsx");
            }

            @Override
            public String getDescription() {
                return "Excel Files (*.xlsx)";
            }
        });

        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            try (FileInputStream fis = new FileInputStream(selectedFile);
                 Workbook workbook = new XSSFWorkbook(fis)) {

                Sheet sheet = workbook.getSheet("DanhSachSach");
                if (sheet == null) {
                    JOptionPane.showMessageDialog(this, "Không tìm thấy sheet 'DanhSachSach' trong file Excel!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                int successCount = 0;
                for (int i = 1; i <= sheet.getLastRowNum(); i++) { // Bỏ qua dòng tiêu đề (i=0)
                    Row row = sheet.getRow(i);
                    if (row == null) continue;

                    try {
                        Sach sach = new Sach();
                        sach.setMasach(row.getCell(0).getStringCellValue()); 
                        sach.setTensach(row.getCell(1).getStringCellValue()); // Tên sách
                        sach.setMatacgia((int) row.getCell(2).getNumericCellValue()); // Mã tác giả
                        sach.setManxb((int) row.getCell(3).getNumericCellValue()); // Mã NXB
                        sach.setMatheloai((int) row.getCell(4).getNumericCellValue()); // Mã thể loại
                        sach.setNamxb((int) row.getCell(5).getNumericCellValue()); // Năm XB
                        sach.setSotrang((int) row.getCell(6).getNumericCellValue()); // Số trang
                        sach.setSoluong((int) row.getCell(7).getNumericCellValue()); // Số lượng

                        // Thêm sách vào cơ sở dữ liệu
                        if (sachDAO.addSach(sach)) {
                            successCount++;
                        } else {
                            JOptionPane.showMessageDialog(this, "Không thể thêm sách: " + sach.getTensach(), "Cảnh báo", JOptionPane.WARNING_MESSAGE);
                        }
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, "Lỗi khi đọc dòng " + (i + 1) + ": " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                    }
                }

                // Làm mới bảng sau khi nhập
                loadTableData();
                JOptionPane.showMessageDialog(this, "Đã nhập thành công " + successCount + " sách!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Lỗi khi đọc file Excel: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnNhapDuLieuActionPerformed
    
    private void loadComboBoxes() {
        try {
        List<TacGia> tacgiaList = tacGiaDAO.getAllTacGia();
        cbTacGia.removeAllItems();
        for (TacGia tacgia : tacgiaList) {
            cbTacGia.addItem(tacgia);
        }

        List<NhaXuatBan> nxbList = nxbDAO.getAllNhaXuatBan();
        cbNXB.removeAllItems();
        for (NhaXuatBan nxb : nxbList) {
            cbNXB.addItem(nxb);
        }

        List<TheLoai> theloaiList = theLoaiDAO.getAllTheLoai();
        cbTheLoai.removeAllItems();
        for (TheLoai theloai : theloaiList) {
            cbTheLoai.addItem(theloai);
        }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void loadTableData() {
        try {
            List<Object[]> sachList = sachDAO.getAllSachWithDetails();
            DefaultTableModel model = (DefaultTableModel) tableSach.getModel();
            model.setRowCount(0);
            for(Object[] row : sachList){
                model.addRow(new Object[]{
                    row[0],
                    row[1],
                    row[2],
                    row[3],
                    row[4],
                    row[5],
                    row[6],
                    row[7]
                });
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu sách: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void addSach() {
        try {
            Sach sach = new Sach();
            sach.setMasach(txtMaSach.getText().trim());
            sach.setTensach(txtTenSach.getText().trim());
            sach.setMatacgia(((TacGia) cbTacGia.getSelectedItem()).getMatacgia());
            sach.setManxb(((NhaXuatBan) cbNXB.getSelectedItem()).getManxb());
            sach.setMatheloai(((TheLoai) cbTheLoai.getSelectedItem()).getMatheloai());
            sach.setNamxb(Integer.parseInt(txtNamXB.getText()));
            sach.setSotrang(Integer.parseInt(txtSoTrang.getText()));
            sach.setSoluong(Integer.parseInt(txtSoLuong.getText()));
            
            if (sachDAO.addSach(sach)) {
                JOptionPane.showMessageDialog(this, "Thêm sách thành công!");
                loadTableData();
                clearFields();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm sách thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số hợp lệ cho Năm XB và Số trang!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi thêm sách: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void updateSach() {
        int row = tableSach.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một sách để sửa!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            Sach sach = new Sach();
            sach.setMasach(tableSach.getValueAt(row, 0).toString());            
            sach.setTensach(txtTenSach.getText());
            sach.setMatacgia(((TacGia) cbTacGia.getSelectedItem()).getMatacgia());
            sach.setManxb(((NhaXuatBan) cbNXB.getSelectedItem()).getManxb());
            sach.setMatheloai(((TheLoai) cbTheLoai.getSelectedItem()).getMatheloai());
            sach.setNamxb(Integer.parseInt(txtNamXB.getText()));
            sach.setSotrang(Integer.parseInt(txtSoTrang.getText()));
            sach.setSoluong(Integer.parseInt(txtSoLuong.getText()));
            
            if (sachDAO.updateSach(sach)) {
                JOptionPane.showMessageDialog(this, "Sửa sách thành công!");
                loadTableData();
                clearFields();
            } else {
                JOptionPane.showMessageDialog(this, "Sửa sách thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số hợp lệ cho Năm XB và Số trang!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi sửa sách: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void deleteSach() {
        int row = tableSach.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một sách để xóa!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa sách này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                String masach = tableSach.getValueAt(row, 0).toString(); // Lấy masach dưới dạng String
                if (sachDAO.deleteSach(masach)) {
                    JOptionPane.showMessageDialog(this, "Xóa sách thành công!");
                    loadTableData();
                    clearFields();
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa sách thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Lỗi khi xóa sách: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void searchSach() {
        try {
            String searchText = txtTimKiem.getText().trim();
            String searchCriteria = (String) cbTimKiem.getSelectedItem();

            List<Object[]> sachList = sachDAO.getAllSachWithDetails();
            DefaultTableModel model = (DefaultTableModel) tableSach.getModel();
            model.setRowCount(0);

            for (Object[] row : sachList) {
                boolean match = false;

                // Lấy các giá trị từ mảng Object[] và xử lý kiểu dữ liệu
                String masach = row[0] != null ? row[0].toString() : "";
                String tensach = row[1] != null ? row[1].toString() : "";
                String tentacgia = row[2] != null ? row[2].toString() : "Không xác định";
                String tennxb = row[3] != null ? row[3].toString() : "Không xác định";
                String tentheloai = row[4] != null ? row[4].toString() : "Không xác định";
                Integer namxb = row[5] != null ? (Integer) row[5] : 0;
                Integer sotrang = row[6] != null ? (Integer) row[6] : 0;
                Integer soluong = row[7] != null ? (Integer) row[7] : 0;

                // Kiểm tra tiêu chí tìm kiếm
                if (searchCriteria.equals("Mã sách") && !searchText.isEmpty()) {
                    match = masach.toLowerCase().contains(searchText.toLowerCase());
                } else if (searchCriteria.equals("Tên sách") && !searchText.isEmpty()) {
                    match = tensach.toLowerCase().contains(searchText.toLowerCase());
                } else if (searchCriteria.equals("Tác giả") && !searchText.isEmpty()) {
                    match = tentacgia.toLowerCase().contains(searchText.toLowerCase());
                } else if (searchCriteria.equals("NXB") && !searchText.isEmpty()) {
                    match = tennxb.toLowerCase().contains(searchText.toLowerCase());
                } else if (searchCriteria.equals("Thể loại") && !searchText.isEmpty()) {
                    match = tentheloai.toLowerCase().contains(searchText.toLowerCase());
                } else if (searchText.isEmpty()) {
                    match = true;
                }

                // Nếu thỏa mãn điều kiện tìm kiếm, thêm hàng vào bảng
                if (match) {
                    model.addRow(new Object[]{
                        masach,
                        tensach,
                        tentacgia,
                        tennxb,
                        tentheloai,
                        namxb,
                        sotrang,
                        soluong
                    });
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tìm kiếm sách: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void clearFields() {
        txtMaSach.setText(""); 
        txtTenSach.setText("");
        txtNamXB.setText("");
        txtSoTrang.setText("");
        cbTacGia.setSelectedIndex(0);
        cbNXB.setSelectedIndex(0);
        cbTheLoai.setSelectedIndex(0);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MaSach;
    private javax.swing.JLabel NXB;
    private javax.swing.JLabel NamXuatBan;
    private javax.swing.JLabel NamXuatBan1;
    private javax.swing.JLabel SoTrang;
    private javax.swing.JLabel TacGia;
    private javax.swing.JLabel TenSach;
    private javax.swing.JLabel TheLoai;
    private javax.swing.JLabel TimKiem;
    private javax.swing.JButton btnNhapDuLieu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuatDuLieu;
    private javax.swing.JComboBox<NhaXuatBan> cbNXB;
    private javax.swing.JComboBox<TacGia> cbTacGia;
    private javax.swing.JComboBox<TheLoai> cbTheLoai;
    private javax.swing.JComboBox<String> cbTimKiem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelButton;
    private javax.swing.JPanel panelInfor;
    private javax.swing.JPanel panelTable;
    private javax.swing.JTable tableSach;
    private javax.swing.JTextField txtMaSach;
    private javax.swing.JTextField txtNamXB;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtSoTrang;
    private javax.swing.JTextField txtTenSach;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
