/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.ChucNang;

import Model.DAO.SuKienDAO;
import Model.DAO.NhaXuatBanDAO;
import Model.NhaXuatBan;
import Model.SuKien;
import UI.BasePanel;
import java.awt.Component;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;

import java.time.LocalDate;
import java.time.LocalTime;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JFileChooser;
import javax.swing.JList;

import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
/**
 *
 * @author Asus
 */
public class PanelSuKien extends BasePanel {

    private final SuKienDAO suKienDAO = new SuKienDAO();
    private final NhaXuatBanDAO nxbDAO = new NhaXuatBanDAO();
    public PanelSuKien() {
        initComponents();
        loadComboBoxes();
        loadTableData();
        styleButton(btnthemSuKien);
        styleButton(btnsuaSuKien);
        styleButton(btnxoaSuKien);
        styleButton(btnNhapDuLieu);
        styleButton(btnXuatDuLieu);
        styleTable(tableSuKien);
        txtDateTimeSuKien.setEditable(false);       
        timeSuKien.addTimeChangeListener(e -> updateTxtDateTimeSuKien());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTenSuKien = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        calendarSuKien = new com.github.lgooddatepicker.components.CalendarPanel();
        timeSuKien = new com.github.lgooddatepicker.components.TimePicker();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtDateTimeSuKien = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMoTaSuKien = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbNXB = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        btnNhapDuLieu = new javax.swing.JButton();
        btnXuatDuLieu = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnthemSuKien = new javax.swing.JButton();
        btnsuaSuKien = new javax.swing.JButton();
        btnxoaSuKien = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableSuKien = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(1120, 666));
        setMinimumSize(new java.awt.Dimension(1120, 666));
        setPreferredSize(new java.awt.Dimension(1120, 666));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setText("Tên sự kiện");
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        txtTenSuKien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thời gian tổ chức sự kiện", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 13))); // NOI18N

        jLabel1.setText("Ngày tổ chức");
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jLabel3.setText("Giờ tổ chức");
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtDateTimeSuKien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateTimeSuKienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(calendarSuKien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtDateTimeSuKien)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(timeSuKien, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calendarSuKien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(26, 26, 26)
                                .addComponent(timeSuKien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(txtDateTimeSuKien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        txtMoTaSuKien.setColumns(20);
        txtMoTaSuKien.setLineWrap(true);
        txtMoTaSuKien.setRows(5);
        txtMoTaSuKien.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtMoTaSuKien);

        jLabel4.setText("Mô tả sự kiện");
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jLabel6.setText("Nhà tài trợ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenSuKien))
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(cbNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTenSuKien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnNhapDuLieu.setText("Nhập dữ liệu");
        btnNhapDuLieu.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnNhapDuLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapDuLieuActionPerformed(evt);
            }
        });

        btnXuatDuLieu.setText("Xuất dữ liệu");
        btnXuatDuLieu.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnXuatDuLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatDuLieuActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Các chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 13))); // NOI18N

        btnthemSuKien.setText("Thêm sự kiện");
        btnthemSuKien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnthemSuKien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemSuKienActionPerformed(evt);
            }
        });

        btnsuaSuKien.setText("Sửa sự kiện");
        btnsuaSuKien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnsuaSuKien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaSuKienActionPerformed(evt);
            }
        });

        btnxoaSuKien.setText("Xóa sự kiện");
        btnxoaSuKien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnxoaSuKien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaSuKienActionPerformed(evt);
            }
        });

        jLabel5.setText("Tìm kiếm");
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtTimKiem.setText("(Tên sự kiện)");

        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnxoaSuKien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnsuaSuKien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnthemSuKien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(btnTimKiem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(12, 12, 12))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnthemSuKien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsuaSuKien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnxoaSuKien)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReset)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnXuatDuLieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNhapDuLieu, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNhapDuLieu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXuatDuLieu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        tableSuKien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sự kiện", "Tên sự kiện", "NXB tài trợ", "Thời gian tổ chức", "Mô tả sự kiện"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableSuKien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSuKienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableSuKien);
        if (tableSuKien.getColumnModel().getColumnCount() > 0) {
            tableSuKien.getColumnModel().getColumn(0).setResizable(false);
            tableSuKien.getColumnModel().getColumn(0).setPreferredWidth(5);
            tableSuKien.getColumnModel().getColumn(1).setResizable(false);
            tableSuKien.getColumnModel().getColumn(1).setPreferredWidth(200);
            tableSuKien.getColumnModel().getColumn(2).setResizable(false);
            tableSuKien.getColumnModel().getColumn(2).setPreferredWidth(200);
            tableSuKien.getColumnModel().getColumn(3).setResizable(false);
            tableSuKien.getColumnModel().getColumn(3).setPreferredWidth(100);
            tableSuKien.getColumnModel().getColumn(4).setResizable(false);
            tableSuKien.getColumnModel().getColumn(4).setPreferredWidth(200);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXuatDuLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatDuLieuActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Chọn nơi lưu file Excel");
        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            if (!fileToSave.getAbsolutePath().endsWith(".xlsx")) {
                fileToSave = new File(fileToSave.getAbsolutePath() + ".xlsx");
            }

            try (Workbook workbook = new XSSFWorkbook()) {
                Sheet sheet = workbook.createSheet("DanhSachSuKien");
                DefaultTableModel model = (DefaultTableModel) tableSuKien.getModel();

                // Ghi header
                Row header = sheet.createRow(0);
                for (int i = 0; i < model.getColumnCount(); i++) {
                    Cell cell = header.createCell(i);
                    cell.setCellValue(model.getColumnName(i));
                }

                // Ghi dữ liệu
                for (int i = 0; i < model.getRowCount(); i++) {
                    Row row = sheet.createRow(i + 1);
                    for (int j = 0; j < model.getColumnCount(); j++) {
                        Object value = model.getValueAt(i, j);
                        row.createCell(j).setCellValue(value != null ? value.toString() : "");
                    }
                }

                try (FileOutputStream fos = new FileOutputStream(fileToSave)) {
                    workbook.write(fos);
                    JOptionPane.showMessageDialog(this, "Xuất file Excel thành công: " + fileToSave.getAbsolutePath());
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Lỗi khi xuất Excel: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnXuatDuLieuActionPerformed

    private void btnthemSuKienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemSuKienActionPerformed
        // TODO add your handling code here:
        addSuKien();
    }//GEN-LAST:event_btnthemSuKienActionPerformed

    private void btnsuaSuKienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaSuKienActionPerformed
        updateSuKien();
    }//GEN-LAST:event_btnsuaSuKienActionPerformed

    private void btnxoaSuKienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaSuKienActionPerformed
        deleteSuKien();
    }//GEN-LAST:event_btnxoaSuKienActionPerformed

    private void tableSuKienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSuKienMouseClicked
        // TODO add your handling code here:
        int row = tableSuKien.getSelectedRow();
                if (row >= 0) {
                    txtTenSuKien.setText(tableSuKien.getValueAt(row, 1).toString());
                    txtDateTimeSuKien.setText(tableSuKien.getValueAt(row, 3).toString());
                    txtMoTaSuKien.setText(tableSuKien.getValueAt(row, 4).toString());
                    int manxb = Integer.parseInt(tableSuKien.getValueAt(row, 2).toString());
                    
                    for (int i = 0; i < cbNXB.getItemCount(); i++) {
                    if (cbNXB.getItemAt(i).getManxb() == manxb) {
                        cbNXB.setSelectedIndex(i);
                        break;
                    }
                }
                }
    }//GEN-LAST:event_tableSuKienMouseClicked

    private void txtDateTimeSuKienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateTimeSuKienActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtDateTimeSuKienActionPerformed

    private void btnNhapDuLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapDuLieuActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Chọn file Excel để nhập");
        int userSelection = fileChooser.showOpenDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();

            try (Workbook workbook = new XSSFWorkbook(file)) {
                Sheet sheet = workbook.getSheetAt(0);
                int successCount = 0, errorCount = 0;
                StringBuilder errorLog = new StringBuilder();

                boolean skipHeader = true;
                for (Row row : sheet) {
                    if (skipHeader) {
                        skipHeader = false;
                        continue;
                    }

                    try {
                        String tenSuKien = row.getCell(0).toString().trim();
                        String tenNXB = row.getCell(1).toString().trim();
                        String tgToChucStr = row.getCell(2).toString().trim();
                        String moTa = row.getCell(3) != null ? row.getCell(3).toString().trim() : "";

                        // Validate dữ liệu
                        if (tenSuKien.isEmpty() || tenNXB.isEmpty() || tgToChucStr.isEmpty() || moTa.isEmpty()) {
                            throw new Exception("Thiếu dữ liệu bắt buộc");
                        }

                        // Regex kiểm tra tên sự kiện
                        if (!tenSuKien.matches("^[\\p{L}\\s]+$")) {
                            throw new Exception("Tên sự kiện không hợp lệ (không được có ký tự đặc biệt, chữ & số phải cách nhau)");
                        }

                        // Tìm nhà xuất bản theo tên
                        NhaXuatBanDAO nxbDAO = new NhaXuatBanDAO();
                        NhaXuatBan nxb = nxbDAO.findByTenNXB(tenNXB);
                        if (nxb == null) throw new Exception("Không tìm thấy nhà xuất bản: " + tenNXB);

                        // Chuyển đổi thời gian tổ chức
                        LocalDateTime tgiantochuc = LocalDateTime.parse(tgToChucStr, DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm"));

                        SuKien sk = new SuKien();
                        sk.setTensukien(tenSuKien);
                        sk.setManxb(nxb.getManxb());
                        sk.setTgiantochuc(tgiantochuc);
                        sk.setMota(moTa);

                        if (suKienDAO.themSuKien(sk)) {
                            successCount++;
                        } else {
                            throw new Exception("Không thể thêm sự kiện vào CSDL");
                        }
                    } catch (Exception exRow) {
                        errorCount++;
                        errorLog.append("Dòng ").append(row.getRowNum() + 1).append(": ")
                                .append(exRow.getMessage()).append("\n");
                        exRow.printStackTrace();
                    }
                }

                loadTableData();
                JOptionPane.showMessageDialog(this,
                    "Đã nhập: " + successCount + " dòng, lỗi: " + errorCount +
                    (errorCount > 0 ? "\n\nChi tiết:\n" + errorLog.toString() : "")
                );

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Lỗi khi đọc file Excel: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnNhapDuLieuActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        searchTheoTenSuKien();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtTimKiem.setText("");
        loadTableData();
    }//GEN-LAST:event_btnResetActionPerformed
        
    private void updateTxtDateTimeSuKien() {
    try {
        LocalDate selectedDate = calendarSuKien.getSelectedDate(); // đã là LocalDate
        LocalTime selectedTime = timeSuKien.getTime();

        if (selectedDate != null && selectedTime != null) {
            LocalDateTime dateTime = LocalDateTime.of(selectedDate, selectedTime); // không cần chuyển đổi gì thêm
            String formatted = dateTime.format(DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm"));
            txtDateTimeSuKien.setText(formatted);
        }
    } catch (Exception e) {
        txtDateTimeSuKien.setText(""); // Nếu lỗi thì xóa nội dung
    }
}

    private void loadComboBoxes() {
        try {
            // Tải Nhà Xuất Bản
            List<NhaXuatBan> nxbList = nxbDAO.getAllNhaXuatBan();
            for (NhaXuatBan nxb : nxbList) {
                cbNXB.addItem(nxb);
            }
            cbNXB.setRenderer(new DefaultListCellRenderer() {
                @Override
                public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                    super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                    if (value instanceof NhaXuatBan) {
                        NhaXuatBan nxb = (NhaXuatBan) value;
                        setText(nxb.getTennxb());
                    }
                    return this;
                }
            });
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void loadTableData() {
        try {
            List<Object[]> skList = suKienDAO.getAllSuKienWithDetails(); // đã chuẩn hóa DAO để trả về List<Object[]>
            DefaultTableModel model = (DefaultTableModel) tableSuKien.getModel();
            model.setRowCount(0); // Xóa dữ liệu cũ

            // Định dạng LocalDateTime
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm");

            for (Object[] row : skList) {
                String formattedDateTime = "";
                if (row[3] != null && row[3] instanceof LocalDateTime) {
                    formattedDateTime = ((LocalDateTime) row[3]).format(formatter);
                }
                model.addRow(new Object[] {
                    row[0], // masukien
                    row[1], // tensukien
                    row[2], // tennxb (đã lấy từ SQL, không cần tra lại)
                    formattedDateTime, // tgiantochuc định dạng
                    row[4]  // mota
                });
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu sự kiện: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    

    private void addSuKien() {
        try {
            // Tạo đối tượng SuKien
            SuKien suKien = new SuKien();
            suKien.setTensukien(txtTenSuKien.getText().trim());
            suKien.setMota(txtMoTaSuKien.getText().trim());

            // Lấy ngày và giờ từ DatePicker và TimePicker
            LocalDate selectedDate = calendarSuKien.getSelectedDate();
            LocalTime selectedTime = timeSuKien.getTime();

            // Kiểm tra dữ liệu đầu vào
            if (selectedDate == null || selectedTime == null || suKien.getTensukien().isEmpty() || suKien.getMota().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ: tên, mô tả, ngày và giờ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Kiểm tra nhà xuất bản được chọn
            NhaXuatBan selectedNXB = (NhaXuatBan) cbNXB.getSelectedItem();
            if (selectedNXB == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn một nhà xuất bản!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Kết hợp ngày và giờ thành LocalDateTime
            LocalDateTime dateTime = LocalDateTime.of(selectedDate, selectedTime);
            suKien.setTgiantochuc(dateTime);

            // Gán manxb từ nhà xuất bản được chọn
            suKien.setManxb(selectedNXB.getManxb());
            
            // Kiểm tra hợp lệ cho tensukien
            String tenSuKien = txtTenSuKien.getText().trim();
            if (tenSuKien.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập tên sự kiện!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 1. Không được chứa ký tự đặc biệt (chỉ cho phép chữ cái, số và khoảng trắng)
            if (!tenSuKien.matches("[\\p{L}\\p{N} ]+")) {
                JOptionPane.showMessageDialog(this, "Tên sự kiện không được chứa ký tự đặc biệt!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 2. Không được dính liền chữ và số (ví dụ: "Sự kiện1" => sai, "Sự kiện 1" => đúng)
            if (tenSuKien.matches(".*[a-zA-Z]\\d.*") || tenSuKien.matches(".*\\d[a-zA-Z].*")) {
                JOptionPane.showMessageDialog(this, "Tên sự kiện không được để chữ và số dính liền nhau (phải có khoảng cách giữa chữ và số)!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            suKien.setTensukien(tenSuKien);
            
            // Định dạng để hiển thị trên txtDateTimeSuKien
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm");
            String formattedDateTime = dateTime.format(formatter);
            txtDateTimeSuKien.setText(formattedDateTime);

            // Thêm vào cơ sở dữ liệu
            if (suKienDAO.themSuKien(suKien)) {
                JOptionPane.showMessageDialog(this, "Thêm sự kiện thành công!");
                // Thêm vào bảng
                DefaultTableModel model = (DefaultTableModel) tableSuKien.getModel();
                model.addRow(new Object[] {
                    suKien.getMasukien(), // Lấy từ cơ sở dữ liệu nếu có RETURN_GENERATED_KEYS
                    suKien.getTensukien(),
                    selectedNXB.getTennxb(), // Hiển thị tên nhà xuất bản
                    formattedDateTime,
                    suKien.getMota()
                });
                loadTableData(); // Tải lại dữ liệu bảng
                clearFields();  // Xóa các trường nhập liệu
            } else {
                JOptionPane.showMessageDialog(this, "Thêm sự kiện thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi thêm sự kiện: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void updateSuKien() {
        int row = tableSuKien.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một sự kiện để sửa!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // Tạo đối tượng SuKien
            SuKien suKien = new SuKien();
            suKien.setMasukien(Integer.parseInt(tableSuKien.getValueAt(row, 0).toString()));
            suKien.setMota(txtMoTaSuKien.getText().trim());

            String tenSuKien = txtTenSuKien.getText().trim();
            if (tenSuKien.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập tên sự kiện!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (!tenSuKien.matches("[\\p{L}\\p{N} ]+")) {
                JOptionPane.showMessageDialog(this, "Tên sự kiện không được chứa ký tự đặc biệt!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (tenSuKien.matches(".*[a-zA-Z]\\d.*") || tenSuKien.matches(".*\\d[a-zA-Z].*")) {
                JOptionPane.showMessageDialog(this, "Tên sự kiện không được để chữ và số dính liền nhau (phải có khoảng cách giữa chữ và số)!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            suKien.setTensukien(tenSuKien);
            
            // Lấy ngày và giờ từ DatePicker và TimePicker
            LocalDate selectedDate = calendarSuKien.getSelectedDate();
            LocalTime selectedTime = timeSuKien.getTime();

            // Kiểm tra dữ liệu đầu vào
            if (selectedDate == null || selectedTime == null || suKien.getTensukien().isEmpty() || suKien.getMota().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ: tên, mô tả, ngày và giờ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Kiểm tra nhà xuất bản được chọn
            NhaXuatBan selectedNXB = (NhaXuatBan) cbNXB.getSelectedItem();
            if (selectedNXB == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn một nhà xuất bản!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Kết hợp ngày và giờ thành LocalDateTime
            LocalDateTime dateTime = LocalDateTime.of(selectedDate, selectedTime);
            suKien.setTgiantochuc(dateTime);

            // Gán manxb từ nhà xuất bản được chọn
            suKien.setManxb(selectedNXB.getManxb());

            // Định dạng để hiển thị trên txtDateTimeSuKien
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm");
            String formattedDateTime = dateTime.format(formatter);
            txtDateTimeSuKien.setText(formattedDateTime);

            if (suKienDAO.updateSuKien(suKien)) {
                JOptionPane.showMessageDialog(this, "Sửa sự kiện thành công!");
                loadTableData();
                clearFields();
            } else {
                JOptionPane.showMessageDialog(this, "Sửa sự kiện thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số hợp lệ", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi sửa sự kiện: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void deleteSuKien() {
        int row = tableSuKien.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một sự kiện để xóa!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa sự kiện này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                int masukien = Integer.parseInt(tableSuKien.getValueAt(row, 0).toString());
                if (suKienDAO.deleteSuKien(masukien)) {
                    JOptionPane.showMessageDialog(this, "Xóa sự kiện thành công!");
                    loadTableData();
                    clearFields();
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa sự kiện thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Lỗi khi xóa sự kiện: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    // Tìm kiếm phiếu mượn theo tên độc giả (Sửa tìm kiếm)
    private void searchTheoTenSuKien() {
    String keyword = txtTimKiem.getText().trim().toLowerCase();
        if (keyword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên sự kiện cần tìm!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            List<Object[]> mpList = suKienDAO.getAllSuKienWithDetails();
            DefaultTableModel model = (DefaultTableModel) tableSuKien.getModel();
            model.setRowCount(0);

            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm");

            for (Object[] row : mpList) {
                int maSuKien = (int) row[0];
                String tenSuKien = (String) row[1];
                String tenNhaTaiTro = (String) row[2];
                LocalDateTime tgToChuc = (LocalDateTime) row[3];
                String moTa = (String) row[4];

                if (!tenSuKien.toLowerCase().contains(keyword)) continue;

                model.addRow(new Object[]{
                    maSuKien,
                    tenSuKien,
                    tenNhaTaiTro,
                    tgToChuc != null ? tgToChuc.format(formatter) : "",
                    moTa
                });
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tìm kiếm: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

private void clearFields() {
        txtTenSuKien.setText("");
        txtDateTimeSuKien.setText("");
        txtMoTaSuKien.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNhapDuLieu;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXuatDuLieu;
    private javax.swing.JButton btnsuaSuKien;
    private javax.swing.JButton btnthemSuKien;
    private javax.swing.JButton btnxoaSuKien;
    private com.github.lgooddatepicker.components.CalendarPanel calendarSuKien;
    private javax.swing.JComboBox<NhaXuatBan> cbNXB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tableSuKien;
    private com.github.lgooddatepicker.components.TimePicker timeSuKien;
    private javax.swing.JTextField txtDateTimeSuKien;
    private javax.swing.JTextArea txtMoTaSuKien;
    private javax.swing.JTextField txtTenSuKien;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
